version: 2

models:

  - name: silver_channels
    description: "Clean and deduplicated data from channels"
    columns:
      - name: channel_id
        description: "Unique ID"
        tests:
          - unique
          - not_null


  - name: silver_deliveries
    description: "Clean and deduplicated data from deliveries"
    columns:
      - name: delivery_id
        description: "Unique delivery ID"
        tests:
          - unique
          - not_null

      - name: delivery_order_id
        description: "Delivery order ID"
        tests:
          - not_null

      - name: driver_id
        description: "Driver ID"
        tests:
          - not_null

  - name: silver_drivers
    description: "Clean and deduplicated data from drivers"
    columns:
      - name: driver_id
        description: "Unique driver ID"
        tests:
          - unique
          - not_null

  - name: silver_hubs
    description: "Clean and deduplicated data from hubs"
    columns:
      - name: hub_id
        description: "Unique hub ID"
        tests:
          - unique
          - not_null

  - name: silver_orders
    description: "Clean and deduplicated data from orders"
    columns:
      - name: order_id
        description: "Unique order ID"
        tests:
          - unique
          - not_null

      - name: store_id
        description: "Store ID"
        tests:
          - not_null

      - name: channel_id
        description: "Sales channel ID"
        tests:
          - not_null

      - name: payment_order_id
        description: "Payment ID"
        tests:
          - not_null

      - name: delivery_order_id
        description: "Delivery order ID"
        tests:
          - not_null

  - name: silver_payments
    description: "Clean and deduplicated data from payments"
    columns:
      - name: payment_id
        description: "Unique payment ID"
        tests:
          - unique
          - not_null

      - name: payment_order_id
        description: "Payment order ID"
        tests:
          - not_null

  - name: silver_stores
    description: "Clean and deduplicated data from stores"
    columns:
      - name: store_id
        description: "Unique store ID"
        tests:
          - unique
          - not_null

      - name: hub_id
        description: "Hub ID"
        tests:
          - not_null